export type GithubRepoVisibility = "public" | "private";

export type GithubRepository = {
  id: string;
  owner: string;
  name: string;
  visibility: GithubRepoVisibility;
  language: string;
  updated: string;
  defaultBranch: string;
  branches: string[];
  description?: string;
};

export type GithubIdentity = {
  login: string;
  name: string;
};

export type GithubConnectionState = "disconnected" | "connecting" | "connected";

export type GithubSyncPhase = "idle" | "syncing" | "checking" | "comparing" | "done" | "error";

export type GithubCheckStatus = "passing" | "failed";

export type GithubCheck = {
  label: string;
  status: GithubCheckStatus;
};

export type GithubPrStatus = "open" | "merged" | "closed";

export type GithubPullRequest = {
  number: number;
  repoId: string;
  title: string;
  description: string;
  author: string;
  base: string;
  compare: string;
  changedFiles: number;
  checks: GithubCheck[];
  status: GithubPrStatus;
  createdTime: string;
};

export type GithubSnapshot = {
  connected: boolean;
  repoId: string | null;
  branch: string | null;
  lastSyncedAt: string | null;
  pushedHead: string | null;
  pullRequests: GithubPullRequest[];
  createdBranches: string[];
  createdRepositories: GithubRepository[];
  demoFailures: boolean;
};

export const githubIdentity: GithubIdentity = {
  login: "abhay-demo",
  name: "Abhay (Demo)",
};

export const githubDemoRepositories: GithubRepository[] = [
  {
    id: "saas-analytics",
    owner: "Abhay-demo",
    name: "saas-analytics",
    visibility: "public",
    language: "TypeScript",
    updated: "12 minutes ago",
    defaultBranch: "main",
    branches: ["main", "develop", "feature/dashboard", "feature/analytics"],
    description: "Analytics dashboard generated by Architect for this project.",
  },
  {
    id: "architect-demo",
    owner: "Abhay-demo",
    name: "architect-demo",
    visibility: "private",
    language: "TypeScript",
    updated: "2 hours ago",
    defaultBranch: "main",
    branches: ["main", "develop"],
    description: "Sample workspace used to try out Architect builds.",
  },
  {
    id: "customer-portal",
    owner: "Abhay-demo",
    name: "customer-portal",
    visibility: "private",
    language: "TypeScript",
    updated: "1 day ago",
    defaultBranch: "main",
    branches: ["main", "feature/portal"],
    description: "Customer self-service portal prototype.",
  },
  {
    id: "sprintboard",
    owner: "Abhay-demo",
    name: "sprintboard",
    visibility: "private",
    language: "TypeScript",
    updated: "4 hours ago",
    defaultBranch: "main",
    branches: ["main", "develop"],
    description: "Kanban project board generated by Architect.",
  },
  {
    id: "ledger-app",
    owner: "Abhay-demo",
    name: "ledger-app",
    visibility: "private",
    language: "TypeScript",
    updated: "6 hours ago",
    defaultBranch: "main",
    branches: ["main", "develop"],
    description: "Personal finance tracker generated by Architect.",
  },
  {
    id: "startup-landing",
    owner: "Abhay-demo",
    name: "startup-landing",
    visibility: "public",
    language: "TypeScript",
    updated: "3 days ago",
    defaultBranch: "main",
    branches: ["main"],
    description: "Marketing landing page generated from a template.",
  },
  {
    id: "internal-tools",
    owner: "Abhay-demo",
    name: "internal-tools",
    visibility: "private",
    language: "TypeScript",
    updated: "1 week ago",
    defaultBranch: "main",
    branches: ["main", "develop"],
    description: "Internal utilities and shared components.",
  },
];

export const githubChecks: GithubCheck[] = [
  { label: "TypeScript", status: "passing" },
  { label: "ESLint", status: "passing" },
  { label: "Production build", status: "passing" },
  { label: "Preview validation", status: "passing" },
];

export const githubRepoList = githubDemoRepositories.map((repo) => ({
  fullName: `${repo.owner}/${repo.name}`,
  ...repo,
}));

export function repoById(id: string | null | undefined): GithubRepository | undefined {
  if (!id) return undefined;
  return githubDemoRepositories.find((repo) => repo.id === id);
}

export function repoFullName(repo: GithubRepository | undefined): string {
  return repo ? `${repo.owner}/${repo.name}` : "Abhay-demo/saas-analytics";
}

export function dedupeBranches(branches: string[]): string[] {
  return Array.from(new Set(branches));
}

export function mergeBranches(base: string[], created: string[]): string[] {
  return dedupeBranches([...base, ...created]);
}

type SeedPrArgs = {
  repoId: string;
  number: number;
  title: string;
  compare: string;
  changedFiles: number;
  status: GithubPrStatus;
  createdTime: string;
};

function seedPr({ repoId, number, title, compare, changedFiles, status, createdTime }: SeedPrArgs): GithubPullRequest {
  return {
    number,
    repoId,
    title,
    description: "Pull request generated through the Architect workflow in prototype mode.",
    author: "abhay-demo",
    base: "main",
    compare,
    changedFiles,
    checks: [...githubChecks],
    status,
    createdTime,
  };
}

export const seedPullRequests: GithubPullRequest[] = [
  seedPr({ repoId: "saas-analytics", number: 23, title: "Add analytics dashboard", compare: "feature/analytics", changedFiles: 7, status: "open", createdTime: "2 minutes ago" }),
  seedPr({ repoId: "saas-analytics", number: 22, title: "Refine KPI card layout", compare: "feature/dashboard", changedFiles: 4, status: "merged", createdTime: "1 day ago" }),
  seedPr({ repoId: "saas-analytics", number: 21, title: "Seed sample dashboard data", compare: "develop", changedFiles: 3, status: "closed", createdTime: "3 days ago" }),
  seedPr({ repoId: "architect-demo", number: 12, title: "Add project templates", compare: "feature/templates", changedFiles: 6, status: "merged", createdTime: "5 days ago" }),
  seedPr({ repoId: "customer-portal", number: 8, title: "Add sign-in flow", compare: "feature/portal", changedFiles: 5, status: "open", createdTime: "1 week ago" }),
];

export function nextPrNumber(pullRequests: GithubPullRequest[]): number {
  const max = pullRequests.reduce((highest, pr) => Math.max(highest, pr.number), 23);
  return max + 1;
}

export const defaultGithubSnapshot: GithubSnapshot = {
  connected: false,
  repoId: null,
  branch: "main",
  lastSyncedAt: null,
  pushedHead: null,
  pullRequests: [],
  createdBranches: [],
  createdRepositories: [],
  demoFailures: false,
};

export const githubSimulatedNote = "GitHub connection is simulated in prototype mode.";
export const githubPrSimulatedNote = "Pull request is simulated. Nothing was created on GitHub.";
export const githubMergeSimulatedNote = "Merge is simulated. The PR status changed in local state only.";
export const githubOAuthNote = "GitHub OAuth is simulated. You will never be asked for a real token or password.";
export const githubConnectedNote = "Connection state is stored in this browser only and is not sent anywhere.";
export const githubSyncSteps = ["Syncing...", "Checking repository...", "Comparing changes...", "Sync complete"];